fix-currency-display
balancednetwork/balanced-network-interface pull request #1054
Opened 2022-08-05 15:11 UTC by molly-tran

2022-08-08 04:31 UTC, shallcdn requested changes
Please update as my comment

2022-08-08 04:31 UTC, shallcdn commented on src/app/components/trade/LiquidityDetails.tsx
> +          {aBalance.currency.symbol == 'bnUSD' ||
Should use '===' instead of  '=='

2022-08-08 14:06 UTC, shallcdn approved these changes
LGTM

2022-08-10 02:42 UTC, BennyOptions commented
Hey @molly-tran @shallcdn this should not be a hard-coded solution. There is always a base_currency and quote_currency. Base is on the left, quote is on the right. Something is incorrect in the logic of the app, simple hard coding is not the ideal solution.

2022-08-10 02:43 UTC, BennyOptions commented
Also, can you guys set this PR to main net so I can test with my wallets that have liquidity? Otherwise I need to get more test tokens which will take more time.

2022-08-10 15:13 UTC, shallcdn commented
> Also, can you guys set this PR to main net so I can test with my wallets that have liquidity? Otherwise I need to get more test tokens which will take more time.

@BennyOptions I have deployed the current change with prod environment, please take a look!

2022-08-10 21:56 UTC, BennyOptions commented
> > Hey @molly-tran @shallcdn this should not be a hard-coded solution. There is always a base_currency and quote_currency. Base is on the left, quote is on the right. Something is incorrect in the logic of the app, simple hard coding is not the ideal solution, because it will display new pools incorrectly.
> 
> Hi @BennyOptions Where can I check the correct order of the pool pairs? on this page, https://stats.balanced.network/ Am I correct?

Yes that's correct.

Also, as a rule, sICX is always on the right side (except for sICX/bnUSD). bnUSD is also always on the right side (never any exceptions)

2022-08-10 21:58 UTC, BennyOptions commented
The "your supply" column is still backwards.

<img width="608" alt="Screen Shot 2022-08-10 at 2 57 27 PM" src="https://user-images.githubusercontent.com/43685868/184027784-df61a200-0d92-4b8c-bbbf-8ec985462590.png">

2022-08-10 21:59 UTC, BennyOptions commented
One thing that confuses me, @shallcdn do you know why sICX/bnUSD is correct, but all others are incorrect?

2022-08-12 11:19 UTC, shallcdn commented
> One thing that confuses me, @shallcdn do you know why sICX/bnUSD is correct, but all others are incorrect?
@BennyOptions 
I have investigated this issue, there is a logic to checking and comparing between two addresses of the base token and quote token to create a pair, 

Eg: Suppose that we have sICX and BALN
sICX address (): 'abd' 
BALN address: 'abc'

The logic will compare 'abd' < 'abc', it will return `false` and create a pair is BALN/sICX, if `true` the pair will be sICX/BALN. 

[JavaScript uses the so-called "dictionary" or "lexicographical" order.](https://javascript.info/comparison#string-comparison) that's why 'abd' is greater than 'abc'

I'm not sure why we used this logic, @octocat512 @hetfly. Do you know why we use this logic to create a Pair?

2022-08-17 12:24 UTC, shallcdn commented
PR https://github.com/balancednetwork/balanced-network-interface/pull/1061 fixed issue #1050 so I close this PR

2022-08-17 12:24 UTC, closed without merging