feat: 🎸 update new api and add all time rebalancing
balancednetwork/balanced-network-interface pull request #546
Opened 2021-07-12 11:23 UTC by hieunguyenebox

2021-07-16 14:11 UTC, hieunguyenebox commented
@tuan-tl @parrot9design  please review

2021-07-18 05:24 UTC, parrot9design requested changes
This is looking great! It doesn't seem like the data is being updated from the backend right now, as the values weren't changing.

I also noticed this glitch in the amount of padding when viewed in a smaller window: 

https://user-images.githubusercontent.com/63842577/126056750-dda58a96-aa9b-40c3-b6e6-05cb535e564d.mov

2021-07-26 03:50 UTC, WeiLi512 requested changes

2021-07-26 03:50 UTC, WeiLi512 commented on .gitignore
> +# test
What is it for?

2021-07-26 03:50 UTC, WeiLi512 commented on src/store/loan/hooks.ts
> +          dispatch(
why do you use redux?

2021-07-26 03:50 UTC, WeiLi512 commented on src/store/loan/hooks.ts
> +          dispatch(
just use react-query. please reference the other part code.

2021-07-26 03:50 UTC, WeiLi512 commented on src/app/components/home/PositionDetailPanel.tsx
> +                      <MenuItem
Please try it.
`<MenuItem className="border-top" />`

2021-07-26 11:20 UTC, hieunguyenebox commented
@parrot9design , fixed, please check again

2021-07-26 12:27 UTC, WeiLi512 approved these changes

2021-07-26 12:27 UTC, WeiLi512 commented on src/app/components/home/PositionDetailPanel.tsx
> +import { timeStamp } from 'console';
the var is useless.

2021-07-26 12:27 UTC, WeiLi512 commented on src/queries/queryRebalancing.ts
> +import axios from 'axios';
remove the file.

2021-07-26 12:27 UTC, WeiLi512 commented on src/app/components/home/PositionDetailPanel.tsx
> +  const [timestamp, setTimeStamp] = useState(dayjs().subtract(1, 'day').unix());
calculate the `timestamp` from `period` var.

2021-07-26 12:27 UTC, WeiLi512 commented on src/app/components/home/PositionDetailPanel.tsx
> +    let timestamp = 0; // all
put the code outside of this funtion.

2021-07-26 12:30 UTC, WeiLi512 requested changes

2021-07-26 12:30 UTC, WeiLi512 commented on src/app/components/home/PositionDetailPanel.tsx
> +  const [timestamp, setTimeStamp] = useState(dayjs().subtract(1, 'day').unix());
.

2021-07-26 19:46 UTC, parrot9design approved these changes

2021-07-27 03:20 UTC, BennyOptions commented
This works for me now @tuan-tl. I checked and the numbers match

2021-07-27 07:25 UTC, WeiLi512 requested changes

2021-07-27 08:24 UTC, WeiLi512 approved these changes

2021-07-27 10:39 UTC, merged