Fix: update claiming ICX content
balancednetwork/balanced-network-interface pull request #698
Opened 2021-09-23 17:08 UTC by Chunn

2021-10-06 03:06 UTC, BennyOptions commented
Still broken, here is the situation:

I unstaked 1 sICX

Transaction: https://tracker.icon.foundation/transaction/0x3183a92912dabbd8ec036442f55c4de53e316a917ba9984b5007a5d279074473

See the result on the UI below. It displays two activities:

1.) Unstaked 1 sICX - CORRECT
2.) Claimed 1.05 ICX - INCORRECT

Only the first transaction should be displayed. Nothing was claimed yet, so it should not display any claim transactions
<img width="1034" alt="Screen Shot 2021-10-05 at 11 03 56 PM" src="https://user-images.githubusercontent.com/43685868/136134219-abb0015c-040b-40a6-9214-75471c1462d4.png">

2021-10-29 20:26 UTC, BennyOptions approved these changes
UI works properly now, thanks!

2021-11-02 07:36 UTC, octocat512 requested changes

2021-11-02 07:36 UTC, octocat512 commented on src/queries/history/index.ts
> +export const useInternalTransactionQuery = (transaction_hash: string) => {
Please use camelCase. @Chunn

2021-11-02 07:41 UTC, merged