Feat/implement DAO Spending proposal
balancednetwork/balanced-network-interface pull request #708
Opened 2021-09-30 17:01 UTC by Chunn

2021-10-01 01:53 UTC, parrot9design commented
Do we want people to be able to direct the funding towards more than one address? The `Add another asset` link was only intended for additional assets, not additional addresses.

2021-10-01 04:47 UTC, BennyOptions commented
@parrot9design that is correct.

@Chunn please remove additional address lines

<img width="967" alt="Screen Shot 2021-10-01 at 12 46 28 AM" src="https://user-images.githubusercontent.com/43685868/135566659-b9a5a24c-fd61-4bfb-8661-7b41dbcdad87.png">

2021-10-01 16:19 UTC, Chunn commented
@parrot9design @BennyOptions Regarding this point, I've created UI based on the sample action parameter. Please check https://bicon.tracker.solidwallet.io/transaction/0x86b672e5ea7a63f569dfaee34c3bd88ffd84bdd4bd8f62f42f460040c82b4fe3
```{
    "_recipient": "hx3f01840a599da07b0f620eeae7aa9c574169a4be",
    "_amounts": [
        {
            "address": "cxae6334850f13dfd8b50f8544d5acb126bb8ef82d",
            "amount": 10000000000000000000
        },
        {
            "address": "cxc48c9c81ceef04445c961c5cc8ff056d733dfe3a",
            "amount": 10000000000000000000
        }
    ]
}
```
I'll remove the address field based @BennyOptions comment. Could you confirm for me what the data type of `_amount` will be?
Because we have only one address => It seems actions params should be
 ```{
    "_recipient": "hx3f01840a599da07b0f620eeae7aa9c574169a4be",
    "_address": "cxae6334850f13dfd8b50f8544d5acb126bb8ef82d",
    "_amounts": [
        {
            "amount": 10000000000000000000,
            "symbol": "BALN"
        },
        {
            "amount": 10000000000000000000,
            "symbol": "sICX"
        }
    ]
}
```
Please help me confirm. Thank you!

2021-10-03 20:56 UTC, parrot9design commented
There's a bug at the moment, where if you add all possible assets and then click `Add another asset` again, you get a white screen. Once all available assets have been listed, we should remove that text link to prevent people getting into trouble.

I also noticed that once you add another asset field, you can't submit the proposal until you add a value to it. We should allow people to submit the proposal as long as at least one asset has a value specified. Any assets selected that don't have a value should be ignored when submitting.

2021-10-04 10:36 UTC, Chunn commented
@parrot9design I've updated based on your comment. Please check again. Thank you!

2021-10-05 02:02 UTC, parrot9design commented
> I've updated based on your comment. Please check again. Thank you!

This is looking great now, thank you!

2021-10-05 02:02 UTC, parrot9design approved these changes

2021-10-06 02:45 UTC, octocat512 requested changes

2021-10-06 02:45 UTC, octocat512 commented on src/app/components/CurrencyInputPanel/index.tsx
> +  balanceList,
I'd like to make `balanceList` data type as   `[key: string]: BigNumber;`

2021-10-06 02:45 UTC, octocat512 commented on src/app/components/CurrencyInputPanel/index.tsx
> +  balanceList,
I will refactor the code. after that,  please review @Chunn

2021-10-06 03:00 UTC, octocat512 commented on src/app/components/CurrencyInputPanel/index.tsx
> +  balanceList,
In the future, the bignumber data type will be changed with `CurrencyAmount` data type.

2021-10-06 03:10 UTC, BennyOptions approved these changes
approve

2021-10-06 03:20 UTC, merged