Refactor/use currency amount for wallet store
balancednetwork/balanced-network-interface pull request #828
Opened 2021-12-26 01:26 UTC by lijac

Close #774

2022-01-11 08:10 UTC, octocat512 requested changes

2022-01-11 08:10 UTC, octocat512 commented on src/store/wallet/hooks.ts
>  export function useWalletFetchBalances(account?: string | null) {
After this refactoring, I thought that we can remove the wallet redux store. 
I think that we can `useWalletFetchBalances` hook and move the logic into the `useWalletBalances` hook.

2022-01-11 08:14 UTC, octocat512 requested changes

2022-01-11 08:14 UTC, octocat512 commented on src/store/wallet/hooks.ts
>  export function useWalletFetchBalances(account?: string | null) {
then we can remove this code.
https://github.com/balancednetwork/balanced-network-interface/blob/4a330afa77acfadc5590eb937f0f56e62da7a229/src/app/containers/TradePage/index.tsx#L22

2022-02-03 06:23 UTC, lijac commented
On Sejong network, swapping bnUSD for ICX fails. The error says:

InvalidParameter in updateBatchRewardsData

https://sejong.tracker.solidwallet.io/transaction/0x4ebe5eb007aa2f45353293222552c87e2136553e679d8a5db07faf4ae0ae425e

2022-02-03 06:29 UTC, lijac commented
> On Sejong network, swapping bnUSD for ICX fails. The error says:
> 
> InvalidParameter in updateBatchRewardsData
> 
> https://sejong.tracker.solidwallet.io/transaction/0x4ebe5eb007aa2f45353293222552c87e2136553e679d8a5db07faf4ae0ae425e

@octocat512 @BennyOptions @gedanziger What would you suggest on this?

2022-02-09 03:53 UTC, octocat512 commented
@lijac we need to reduce using bignumber by using new data structures. please refactor the code again by removing bignumber usage.

2022-02-23 04:47 UTC, octocat512 commented
Please resolve conflicts. @lijac

2022-02-25 15:11 UTC, merged