feat: add FIN token
balancednetwork/balanced-network-interface pull request #853
Opened 2022-01-15 14:52 UTC by Chunn

2022-01-17 01:39 UTC, octocat512 requested changes

2022-01-17 01:39 UTC, octocat512 commented on src/constants/currency.ts
> +    cx785d504f44b5d2c8dac04c5a1ecd75f18ee57d16: 'FIN',
The `addressToCurrecyKeyMap` will keep three tokens that the BalancedDAO fund has. sICX, bnUSD, BALN. You don't need to add `FIN` token here.

2022-01-17 01:39 UTC, octocat512 commented on src/constants/pairs.ts
> +      name: 'FIN/BnUSD',
`FIN/bnUSD`

2022-01-17 01:39 UTC, octocat512 commented on src/packages/BalancedJs/addresses.ts
> +  fin: 'cx785d504f44b5d2c8dac04c5a1ecd75f18ee57d16',
The variable only keeps the addresses related to the Balanced Network. remove fin token address.

2022-01-20 01:51 UTC, rise-techiast approved these changes

2022-01-20 01:52 UTC, octocat512 approved these changes

2022-01-20 12:55 UTC, merged