feat: add keyboard control to currency select
balancednetwork/balanced-network-interface pull request #908
Opened 2022-02-28 21:11 UTC by hetfly

2022-03-07 10:08 UTC, hetfly commented
@parrot9design focusing input on dropdown show isn't happening on mobile since the keyboard would automatically popup

2022-03-08 04:44 UTC, parrot9design commented
This looks good, thanks @hetfly!

The only issue I noticed is that the search doesn't always work as expected. Examples:
<img width="361" alt="Screen Shot 2022-03-08 at 5 39 27 PM" src="https://user-images.githubusercontent.com/63842577/157167408-ad32bce6-0e3c-4968-bc89-7e803e0d7cb7.png"><img width="351" alt="Screen Shot 2022-03-08 at 5 39 35 PM" src="https://user-images.githubusercontent.com/63842577/157167415-f1196ef4-e4ae-423b-b81d-d54672ece01f.png">
<img width="346" alt="Screen Shot 2022-03-08 at 5 40 00 PM" src="https://user-images.githubusercontent.com/63842577/157167422-0096c35e-1889-4809-bbdd-7d453f207ef1.png"><img width="355" alt="Screen Shot 2022-03-08 at 5 39 42 PM" src="https://user-images.githubusercontent.com/63842577/157167419-aca3e7f8-a728-472c-93a6-250b86c4a441.png">

It's not a result of this specific PR (and we can tackle it separately if that makes more sense), but are you able to take a look at this? Both the full token name and the ticker should be searchable.

2022-03-08 11:32 UTC, hetfly commented
@parrot9design opened new PR https://github.com/balancednetwork/balanced-network-interface/pull/916

2022-03-09 08:30 UTC, parrot9design approved these changes

2022-03-11 01:40 UTC, octocat512 requested changes

2022-03-11 01:40 UTC, octocat512 commented on src/app/components/SearchModal/CurrencyList.tsx
> +  setFocusedIndex: React.Dispatch<React.SetStateAction<number | undefined>>;
use `onFocus` instead of `setFocusedIndex`, remove index, and define the function like it.
`onFocus: () => void`

2022-03-11 01:40 UTC, octocat512 commented on src/app/components/SearchModal/CurrencyList.tsx
> +          isFocused={index === focusIndex}
Instead of handling index in child components, handle here.
`onFocus = { () => setFocusIndex(index) }`

2022-03-11 01:40 UTC, octocat512 commented on src/app/components/SearchModal/CurrencySearch.tsx
> +  const escape = useKeyPress('Escape');
Move keyboard control logic in the `CurrencyList` component.

2022-03-12 11:40 UTC, hetfly commented
refactored, thanks for the review! @octocat512

2022-03-15 01:52 UTC, octocat512 approved these changes

2022-03-15 01:53 UTC, merged