Transfer sICX, BALN, bnUSD contract calls
balancednetwork/balanced-network-interface pull request #96
Opened 2021-03-28 15:54 UTC by tuan-tl

2021-03-28 17:10 UTC, BennyOptions commented
Transfer sICX = success
https://bicon.tracker.solidwallet.io/transaction/0x07785b52dea298e3a68e347d84a8955ea9d6a902c7bc9c36e56b2072782e58c4

Send bnUSD = N/A (UI Issue)
- UI does not allow the user to type @WeiLi512 

Stake BALN = N/A (UI Issue)
- Could not verify, I have 0 BALN and the UI does not allow typing @WeiLi512

2021-03-29 02:51 UTC, WeiLi512 requested changes

2021-03-29 02:51 UTC, WeiLi512 commented on src/packages/BalancedJs/contracts/Baln.ts
> +  public async transfer(toAddress: string, value: number): Promise<any> {
I'd like to use the names of the same parameters as names of smart contract method params. 
toAddress -> to

2021-03-29 02:51 UTC, WeiLi512 commented on src/packages/BalancedJs/contracts/Baln.ts
> +  async stakeBALN(value: number): Promise<ResponseJsonRPCPayload> {
I'd like to use the names of the same method as the names of the smart contract method.

2021-03-29 02:51 UTC, WeiLi512 commented on src/packages/BalancedJs/contracts/Baln.ts
> +  async stakeBALN(value: number): Promise<ResponseJsonRPCPayload> {
stakedBALN -> stake

2021-03-29 02:51 UTC, WeiLi512 commented on src/packages/BalancedJs/contracts/bnUSD.ts
> +  public async transfer(toAddress: string, value: number): Promise<any> {
I'd like to use the names of the same parameters as names of smart contract method params.
toAddress -> to

2021-03-29 02:51 UTC, WeiLi512 commented on src/packages/BalancedJs/contracts/sICX.ts
> +  public async transfer(toAddress: string, value: number): Promise<any> {
I'd like to use the names of the same parameters as names of smart contract method params.
toAddress -> to

2021-03-29 02:51 UTC, WeiLi512 commented on src/packages/BalancedJs/contracts/sICX.ts
> +  async unstakeSICX(value: number): Promise<ResponseJsonRPCPayload> {
name convention

2021-03-29 03:47 UTC, WeiLi512 approved these changes

2021-03-29 03:48 UTC, merged